### ISSUE TITLE
Missing libnsl under centos8

### ISSUE THREAD

**Issue by jocheco** [niva83/campaign-planning-tool#6]
Hi Nikola and others,

I was testing the package under CentOS8 and when running the first example I had an issue when importing the package:

> ---> 22 from rasterio._base import gdal_version
>      23 from rasterio.drivers import is_blacklisted
>      24 from rasterio.dtypes import (
> ImportError: libnsl.so.1: cannot open shared object file: No such file or directory

This seems to be related to a missing library in the standard installation. Therefore the solution I have got was:

`sudo yum install libnsl`

Maybe you should add this in the installation notes.

**Comment by niva83** [comment]
@jocheco many thanks! I've added info in README.md
