### ISSUE TITLE
Second lidar positions reduced to 20 in example 1 with Corine land cover v2020 

### ISSUE THREAD

**Issue by jocheco** [niva83/campaign-planning-tool#7]
Hi there,

I was testing examples 1 and 2 with the present Corine Land Cover version U2018_CLC2012_V2020_20u1.tif and for example 1 I realized the second_lidar_positions found are 20.

This breaks the example, since index 26 is asked. 

![image](https://user-images.githubusercontent.com/54977504/98928879-9e2aaf00-24da-11eb-8a4a-fe4560813720.png)

This could be an update to example 1.

**Comment by niva83** [comment]
Many thanks @jocheco for checking the example! 

Would you mind updating notebooks and making pull request at:
https://github.com/niva83/campaign-planning-tool-examples

I will add you as a contributor.

**Comment by niva83** [comment]
Also, as mentioned in the example:
```
Corine Land Cover - 100 meter 2012 Raster 100m GeoTiff You will download a zip file, which contains various files, but you need to point CPT to the tif file, which depending on the landcover data version could have different name. At the time of writing this Jupyter notebook has a following name:
CLC2018_CLC2012_V2018_20.tif
```
and as you encountered, it is hard to predict behaviour unless the exact version of the landcover is used.

**Comment by jocheco** [comment]
I understand your point @niva83. This is really a minor issue. 

To be noted is that Copernicus makes directly available only the latest version of the data.  Sure you can get older versions via a request.

**Comment by niva83** [comment]
@jocheco great! I hope it fine if I close this issue.
